<?php
return [
    'MALE_GENDER' => 1,
    'FEMALE_GENDER' => 0,
    'BUY_TYPE' => 'buy',
    'SELL_TYPE' => 'sell',
    'NUMBER_ITEM_PER_PAGE' => 12,
    'TYPE_POST_WAITING' => 'waiting',
    'TYPE_POST_REJECTED' => 'rejected',
    'TYPE_POST_HIDDEN' => 'hidden',
    'TYPE_POST_ACTIVE' => 'active',
    'ASCENDANT' => 'asc',
    'DESCENDANT' => 'desc',
    'USER_ACTIVE_DIGITAL' => 1,
    'USER_BLOCKED_DIGITAL' => 0,
    'USER_ACTIVE' => 'active',
    'USER_BLOCKED' => 'blocked',
    'ACCOUNT_TYPE_USER' => 'user',
    'ACCOUNT_TYPE_ADMIN' => 'admin',
    'TYPE_NOTIFICATION' => 1,
    'TYPE_MESSAGE' => 2,
];
